/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "auto_scaling_service_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace jiffy { namespace auto_scaling {


auto_scaling_exception::~auto_scaling_exception() throw() {
}


void auto_scaling_exception::__set_msg(const std::string& val) {
  this->msg = val;
}
std::ostream& operator<<(std::ostream& out, const auto_scaling_exception& obj)
{
  obj.printTo(out);
  return out;
}


void swap(auto_scaling_exception &a, auto_scaling_exception &b) {
  using ::std::swap;
  swap(a.msg, b.msg);
  swap(a.__isset, b.__isset);
}

auto_scaling_exception::auto_scaling_exception(const auto_scaling_exception& other0) : TException() {
  msg = other0.msg;
  __isset = other0.__isset;
}
auto_scaling_exception& auto_scaling_exception::operator=(const auto_scaling_exception& other1) {
  msg = other1.msg;
  __isset = other1.__isset;
  return *this;
}
void auto_scaling_exception::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "auto_scaling_exception(";
  out << "msg=" << to_string(msg);
  out << ")";
}

const char* auto_scaling_exception::what() const throw() {
  try {
    std::stringstream ss;
    ss << "TException - service has thrown: " << *this;
    this->thriftTExceptionMessageHolder_ = ss.str();
    return this->thriftTExceptionMessageHolder_.c_str();
  } catch (const std::exception&) {
    return "TException - service has thrown: auto_scaling_exception";
  }
}

}} // namespace
