/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef block_service_H
#define block_service_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "block_service_types.h"

namespace elasticmem { namespace storage {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class block_serviceIf {
 public:
  virtual ~block_serviceIf() {}
  virtual void run_command(std::vector<std::string> & _return, const int32_t block_id, const int32_t cmd_id, const std::vector<std::string> & arguments) = 0;
};

class block_serviceIfFactory {
 public:
  typedef block_serviceIf Handler;

  virtual ~block_serviceIfFactory() {}

  virtual block_serviceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(block_serviceIf* /* handler */) = 0;
};

class block_serviceIfSingletonFactory : virtual public block_serviceIfFactory {
 public:
  block_serviceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<block_serviceIf>& iface) : iface_(iface) {}
  virtual ~block_serviceIfSingletonFactory() {}

  virtual block_serviceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(block_serviceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<block_serviceIf> iface_;
};

class block_serviceNull : virtual public block_serviceIf {
 public:
  virtual ~block_serviceNull() {}
  void run_command(std::vector<std::string> & /* _return */, const int32_t /* block_id */, const int32_t /* cmd_id */, const std::vector<std::string> & /* arguments */) {
    return;
  }
};

typedef struct _block_service_run_command_args__isset {
  _block_service_run_command_args__isset() : block_id(false), cmd_id(false), arguments(false) {}
  bool block_id :1;
  bool cmd_id :1;
  bool arguments :1;
} _block_service_run_command_args__isset;

class block_service_run_command_args {
 public:

  block_service_run_command_args(const block_service_run_command_args&);
  block_service_run_command_args& operator=(const block_service_run_command_args&);
  block_service_run_command_args() : block_id(0), cmd_id(0) {
  }

  virtual ~block_service_run_command_args() throw();
  int32_t block_id;
  int32_t cmd_id;
  std::vector<std::string>  arguments;

  _block_service_run_command_args__isset __isset;

  void __set_block_id(const int32_t val);

  void __set_cmd_id(const int32_t val);

  void __set_arguments(const std::vector<std::string> & val);

  bool operator == (const block_service_run_command_args & rhs) const
  {
    if (!(block_id == rhs.block_id))
      return false;
    if (!(cmd_id == rhs.cmd_id))
      return false;
    if (!(arguments == rhs.arguments))
      return false;
    return true;
  }
  bool operator != (const block_service_run_command_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const block_service_run_command_args & ) const;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};


class block_service_run_command_pargs {
 public:


  virtual ~block_service_run_command_pargs() throw();
  const int32_t* block_id;
  const int32_t* cmd_id;
  const std::vector<std::string> * arguments;

  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};

typedef struct _block_service_run_command_result__isset {
  _block_service_run_command_result__isset() : success(false), ex(false) {}
  bool success :1;
  bool ex :1;
} _block_service_run_command_result__isset;

class block_service_run_command_result {
 public:

  block_service_run_command_result(const block_service_run_command_result&);
  block_service_run_command_result& operator=(const block_service_run_command_result&);
  block_service_run_command_result() {
  }

  virtual ~block_service_run_command_result() throw();
  std::vector<std::string>  success;
  block_exception ex;

  _block_service_run_command_result__isset __isset;

  void __set_success(const std::vector<std::string> & val);

  void __set_ex(const block_exception& val);

  bool operator == (const block_service_run_command_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ex == rhs.ex))
      return false;
    return true;
  }
  bool operator != (const block_service_run_command_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const block_service_run_command_result & ) const;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

};

typedef struct _block_service_run_command_presult__isset {
  _block_service_run_command_presult__isset() : success(false), ex(false) {}
  bool success :1;
  bool ex :1;
} _block_service_run_command_presult__isset;

class block_service_run_command_presult {
 public:


  virtual ~block_service_run_command_presult() throw();
  std::vector<std::string> * success;
  block_exception ex;

  _block_service_run_command_presult__isset __isset;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);

};

template <class Protocol_>
class block_serviceClientT : virtual public block_serviceIf {
 public:
  block_serviceClientT(apache::thrift::stdcxx::shared_ptr< Protocol_> prot) {
    setProtocolT(prot);
  }
  block_serviceClientT(apache::thrift::stdcxx::shared_ptr< Protocol_> iprot, apache::thrift::stdcxx::shared_ptr< Protocol_> oprot) {
    setProtocolT(iprot,oprot);
  }
 private:
  void setProtocolT(apache::thrift::stdcxx::shared_ptr< Protocol_> prot) {
  setProtocolT(prot,prot);
  }
  void setProtocolT(apache::thrift::stdcxx::shared_ptr< Protocol_> iprot, apache::thrift::stdcxx::shared_ptr< Protocol_> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return this->piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return this->poprot_;
  }
  void run_command(std::vector<std::string> & _return, const int32_t block_id, const int32_t cmd_id, const std::vector<std::string> & arguments);
  void send_run_command(const int32_t block_id, const int32_t cmd_id, const std::vector<std::string> & arguments);
  void recv_run_command(std::vector<std::string> & _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< Protocol_> piprot_;
  apache::thrift::stdcxx::shared_ptr< Protocol_> poprot_;
  Protocol_* iprot_;
  Protocol_* oprot_;
};

typedef block_serviceClientT< ::apache::thrift::protocol::TProtocol> block_serviceClient;

template <class Protocol_>
class block_serviceProcessorT : public ::apache::thrift::TDispatchProcessorT<Protocol_> {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<block_serviceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
  virtual bool dispatchCallTemplated(Protocol_* iprot, Protocol_* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (block_serviceProcessorT::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef void (block_serviceProcessorT::*SpecializedProcessFunction)(int32_t, Protocol_*, Protocol_*, void*);
  struct ProcessFunctions {
    ProcessFunction generic;
    SpecializedProcessFunction specialized;
    ProcessFunctions(ProcessFunction g, SpecializedProcessFunction s) :
      generic(g),
      specialized(s) {}
    ProcessFunctions() : generic(NULL), specialized(NULL) {}
  };
  typedef std::map<std::string, ProcessFunctions> ProcessMap;
  ProcessMap processMap_;
  void process_run_command(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_run_command(int32_t seqid, Protocol_* iprot, Protocol_* oprot, void* callContext);
 public:
  block_serviceProcessorT(::apache::thrift::stdcxx::shared_ptr<block_serviceIf> iface) :
    iface_(iface) {
    processMap_["run_command"] = ProcessFunctions(
      &block_serviceProcessorT::process_run_command,
      &block_serviceProcessorT::process_run_command);
  }

  virtual ~block_serviceProcessorT() {}
};

typedef block_serviceProcessorT< ::apache::thrift::protocol::TDummyProtocol > block_serviceProcessor;

template <class Protocol_>
class block_serviceProcessorFactoryT : public ::apache::thrift::TProcessorFactory {
 public:
  block_serviceProcessorFactoryT(const ::apache::thrift::stdcxx::shared_ptr< block_serviceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< block_serviceIfFactory > handlerFactory_;
};

typedef block_serviceProcessorFactoryT< ::apache::thrift::protocol::TDummyProtocol > block_serviceProcessorFactory;

class block_serviceMultiface : virtual public block_serviceIf {
 public:
  block_serviceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<block_serviceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~block_serviceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<block_serviceIf> > ifaces_;
  block_serviceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<block_serviceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void run_command(std::vector<std::string> & _return, const int32_t block_id, const int32_t cmd_id, const std::vector<std::string> & arguments) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->run_command(_return, block_id, cmd_id, arguments);
    }
    ifaces_[i]->run_command(_return, block_id, cmd_id, arguments);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
template <class Protocol_>
class block_serviceConcurrentClientT : virtual public block_serviceIf {
 public:
  block_serviceConcurrentClientT(apache::thrift::stdcxx::shared_ptr< Protocol_> prot) {
    setProtocolT(prot);
  }
  block_serviceConcurrentClientT(apache::thrift::stdcxx::shared_ptr< Protocol_> iprot, apache::thrift::stdcxx::shared_ptr< Protocol_> oprot) {
    setProtocolT(iprot,oprot);
  }
 private:
  void setProtocolT(apache::thrift::stdcxx::shared_ptr< Protocol_> prot) {
  setProtocolT(prot,prot);
  }
  void setProtocolT(apache::thrift::stdcxx::shared_ptr< Protocol_> iprot, apache::thrift::stdcxx::shared_ptr< Protocol_> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return this->piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return this->poprot_;
  }
  void run_command(std::vector<std::string> & _return, const int32_t block_id, const int32_t cmd_id, const std::vector<std::string> & arguments);
  int32_t send_run_command(const int32_t block_id, const int32_t cmd_id, const std::vector<std::string> & arguments);
  void recv_run_command(std::vector<std::string> & _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< Protocol_> piprot_;
  apache::thrift::stdcxx::shared_ptr< Protocol_> poprot_;
  Protocol_* iprot_;
  Protocol_* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

typedef block_serviceConcurrentClientT< ::apache::thrift::protocol::TProtocol> block_serviceConcurrentClient;

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}} // namespace

#include "block_service.tcc"
#include "block_service_types.tcc"

#endif
