/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "directory_rpc_service_constants.h"

namespace elasticmem { namespace directory {

const directory_rpc_serviceConstants g_directory_rpc_service_constants;

directory_rpc_serviceConstants::directory_rpc_serviceConstants() {
}

}} // namespace

