#ifndef ELASTICMEM_BLOCK_ALLOCATION_SERVICE_HANDLER_H
#define ELASTICMEM_BLOCK_ALLOCATION_SERVICE_HANDLER_H



class block_allocation_service_handler {

};



#endif //ELASTICMEM_BLOCK_ALLOCATION_SERVICE_HANDLER_H
