#ifndef ELASTICMEM_BLOCK_ALLOCATION_SERVICE_FACTORY_H
#define ELASTICMEM_BLOCK_ALLOCATION_SERVICE_FACTORY_H



class block_allocation_service_factory {

};



#endif //ELASTICMEM_BLOCK_ALLOCATION_SERVICE_FACTORY_H
