include(CMakeDependentOption)

# Components to build
option(BUILD_TESTS "Build with unittests" ON)
option(BUILD_DOC "Build documentation" OFF)
option(BUILD_STORAGE "Build storage service" ON)
option(BUILD_DIRECTORY "Build directory service" ON)
option(BUILD_CPP_CLIENT "Build C++ client" ON)
option(BUILD_PYTHON_CLIENT "Build Python Client" ON)
option(BUILD_JAVA_CLIENT "Build Java Client" ON)
option(USE_SYSTEM_BOOST "Use system boost libraries" OFF)
option(USE_SYSTEM_THRIFT "Use system thrift library" OFF)
option(USE_SYSTEM_AWSSDK "Use system AWS SDK" OFF)
option(USE_SYSTEM_JEMALLOC "Use system Jemalloc" OFF)
option(BUILD_BENCHMARKS "Build benchmarks" OFF)
option(GENERATE_THRIFT "Generate thrift files" OFF)

message(STATUS "----------------------------------------------------------")
message(STATUS "${PROJECT_NAME} version:                        ${PROJECT_VERSION}")
message(STATUS "Build configuration Summary")
message(STATUS "  Build storage service:                  ${BUILD_STORAGE}")
message(STATUS "  Build directory service:                ${BUILD_DIRECTORY}")
message(STATUS "  Build C++ client:                       ${BUILD_CPP_CLIENT}")
message(STATUS "  Build Python client:                    ${BUILD_PYTHON_CLIENT}")
message(STATUS "  Build Java client:                      ${BUILD_JAVA_CLIENT}")
message(STATUS "  Build benchmarks:                       ${BUILD_BENCHMARKS}")
message(STATUS "  Build unit tests:                       ${BUILD_TESTS}")
message(STATUS "  Build documentation:                    ${BUILD_DOC}")
message(STATUS "  Use system thrift library:              ${USE_SYSTEM_THRIFT}")
message(STATUS "  Use system AWS SDK:                     ${USE_SYSTEM_AWSSDK}")
message(STATUS "  Use system Jemalloc:                    ${USE_SYSTEM_JEMALLOC}")
message(STATUS "  Generate thrift files:                  ${GENERATE_THRIFT}")
message(STATUS "----------------------------------------------------------")
