/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package jiffy.directory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)")
public class rpc_file_status implements org.apache.thrift.TBase<rpc_file_status, rpc_file_status._Fields>, java.io.Serializable, Cloneable, Comparable<rpc_file_status> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("rpc_file_status");

  private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField PERMISSIONS_FIELD_DESC = new org.apache.thrift.protocol.TField("permissions", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField LAST_WRITE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("last_write_time", org.apache.thrift.protocol.TType.I64, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new rpc_file_statusStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new rpc_file_statusTupleSchemeFactory();

  /**
   * 
   * @see rpc_file_type
   */
  public @org.apache.thrift.annotation.Nullable rpc_file_type type; // required
  public int permissions; // required
  public long last_write_time; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see rpc_file_type
     */
    TYPE((short)1, "type"),
    PERMISSIONS((short)2, "permissions"),
    LAST_WRITE_TIME((short)3, "last_write_time");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TYPE
          return TYPE;
        case 2: // PERMISSIONS
          return PERMISSIONS;
        case 3: // LAST_WRITE_TIME
          return LAST_WRITE_TIME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PERMISSIONS_ISSET_ID = 0;
  private static final int __LAST_WRITE_TIME_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, rpc_file_type.class)));
    tmpMap.put(_Fields.PERMISSIONS, new org.apache.thrift.meta_data.FieldMetaData("permissions", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "rpc_perms")));
    tmpMap.put(_Fields.LAST_WRITE_TIME, new org.apache.thrift.meta_data.FieldMetaData("last_write_time", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(rpc_file_status.class, metaDataMap);
  }

  public rpc_file_status() {
  }

  public rpc_file_status(
    rpc_file_type type,
    int permissions,
    long last_write_time)
  {
    this();
    this.type = type;
    this.permissions = permissions;
    setPermissionsIsSet(true);
    this.last_write_time = last_write_time;
    setLastWriteTimeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public rpc_file_status(rpc_file_status other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetType()) {
      this.type = other.type;
    }
    this.permissions = other.permissions;
    this.last_write_time = other.last_write_time;
  }

  public rpc_file_status deepCopy() {
    return new rpc_file_status(this);
  }

  @Override
  public void clear() {
    this.type = null;
    setPermissionsIsSet(false);
    this.permissions = 0;
    setLastWriteTimeIsSet(false);
    this.last_write_time = 0;
  }

  /**
   * 
   * @see rpc_file_type
   */
  @org.apache.thrift.annotation.Nullable
  public rpc_file_type getType() {
    return this.type;
  }

  /**
   * 
   * @see rpc_file_type
   */
  public rpc_file_status setType(@org.apache.thrift.annotation.Nullable rpc_file_type type) {
    this.type = type;
    return this;
  }

  public void unsetType() {
    this.type = null;
  }

  /** Returns true if field type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return this.type != null;
  }

  public void setTypeIsSet(boolean value) {
    if (!value) {
      this.type = null;
    }
  }

  public int getPermissions() {
    return this.permissions;
  }

  public rpc_file_status setPermissions(int permissions) {
    this.permissions = permissions;
    setPermissionsIsSet(true);
    return this;
  }

  public void unsetPermissions() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PERMISSIONS_ISSET_ID);
  }

  /** Returns true if field permissions is set (has been assigned a value) and false otherwise */
  public boolean isSetPermissions() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PERMISSIONS_ISSET_ID);
  }

  public void setPermissionsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PERMISSIONS_ISSET_ID, value);
  }

  public long getLastWriteTime() {
    return this.last_write_time;
  }

  public rpc_file_status setLastWriteTime(long last_write_time) {
    this.last_write_time = last_write_time;
    setLastWriteTimeIsSet(true);
    return this;
  }

  public void unsetLastWriteTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LAST_WRITE_TIME_ISSET_ID);
  }

  /** Returns true if field last_write_time is set (has been assigned a value) and false otherwise */
  public boolean isSetLastWriteTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LAST_WRITE_TIME_ISSET_ID);
  }

  public void setLastWriteTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LAST_WRITE_TIME_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((rpc_file_type)value);
      }
      break;

    case PERMISSIONS:
      if (value == null) {
        unsetPermissions();
      } else {
        setPermissions((java.lang.Integer)value);
      }
      break;

    case LAST_WRITE_TIME:
      if (value == null) {
        unsetLastWriteTime();
      } else {
        setLastWriteTime((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TYPE:
      return getType();

    case PERMISSIONS:
      return getPermissions();

    case LAST_WRITE_TIME:
      return getLastWriteTime();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TYPE:
      return isSetType();
    case PERMISSIONS:
      return isSetPermissions();
    case LAST_WRITE_TIME:
      return isSetLastWriteTime();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof rpc_file_status)
      return this.equals((rpc_file_status)that);
    return false;
  }

  public boolean equals(rpc_file_status that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_type = true && this.isSetType();
    boolean that_present_type = true && that.isSetType();
    if (this_present_type || that_present_type) {
      if (!(this_present_type && that_present_type))
        return false;
      if (!this.type.equals(that.type))
        return false;
    }

    boolean this_present_permissions = true;
    boolean that_present_permissions = true;
    if (this_present_permissions || that_present_permissions) {
      if (!(this_present_permissions && that_present_permissions))
        return false;
      if (this.permissions != that.permissions)
        return false;
    }

    boolean this_present_last_write_time = true;
    boolean that_present_last_write_time = true;
    if (this_present_last_write_time || that_present_last_write_time) {
      if (!(this_present_last_write_time && that_present_last_write_time))
        return false;
      if (this.last_write_time != that.last_write_time)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetType()) ? 131071 : 524287);
    if (isSetType())
      hashCode = hashCode * 8191 + type.getValue();

    hashCode = hashCode * 8191 + permissions;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(last_write_time);

    return hashCode;
  }

  @Override
  public int compareTo(rpc_file_status other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetType()).compareTo(other.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, other.type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPermissions()).compareTo(other.isSetPermissions());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPermissions()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.permissions, other.permissions);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLastWriteTime()).compareTo(other.isSetLastWriteTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastWriteTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.last_write_time, other.last_write_time);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("rpc_file_status(");
    boolean first = true;

    sb.append("type:");
    if (this.type == null) {
      sb.append("null");
    } else {
      sb.append(this.type);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("permissions:");
    sb.append(this.permissions);
    first = false;
    if (!first) sb.append(", ");
    sb.append("last_write_time:");
    sb.append(this.last_write_time);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (type == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'type' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'permissions' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'last_write_time' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class rpc_file_statusStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public rpc_file_statusStandardScheme getScheme() {
      return new rpc_file_statusStandardScheme();
    }
  }

  private static class rpc_file_statusStandardScheme extends org.apache.thrift.scheme.StandardScheme<rpc_file_status> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, rpc_file_status struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.type = jiffy.directory.rpc_file_type.findByValue(iprot.readI32());
              struct.setTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PERMISSIONS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.permissions = iprot.readI32();
              struct.setPermissionsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LAST_WRITE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.last_write_time = iprot.readI64();
              struct.setLastWriteTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetPermissions()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'permissions' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetLastWriteTime()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'last_write_time' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, rpc_file_status struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.type != null) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        oprot.writeI32(struct.type.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PERMISSIONS_FIELD_DESC);
      oprot.writeI32(struct.permissions);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LAST_WRITE_TIME_FIELD_DESC);
      oprot.writeI64(struct.last_write_time);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class rpc_file_statusTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public rpc_file_statusTupleScheme getScheme() {
      return new rpc_file_statusTupleScheme();
    }
  }

  private static class rpc_file_statusTupleScheme extends org.apache.thrift.scheme.TupleScheme<rpc_file_status> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, rpc_file_status struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.type.getValue());
      oprot.writeI32(struct.permissions);
      oprot.writeI64(struct.last_write_time);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, rpc_file_status struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.type = jiffy.directory.rpc_file_type.findByValue(iprot.readI32());
      struct.setTypeIsSet(true);
      struct.permissions = iprot.readI32();
      struct.setPermissionsIsSet(true);
      struct.last_write_time = iprot.readI64();
      struct.setLastWriteTimeIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

