/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef block_service_CONSTANTS_H
#define block_service_CONSTANTS_H

#include "block_service_types.h"

namespace jiffy { namespace storage {

class block_serviceConstants {
 public:
  block_serviceConstants();

};

extern const block_serviceConstants g_block_service_constants;

}} // namespace

#endif
