/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef kv_rpc_service_CONSTANTS_H
#define kv_rpc_service_CONSTANTS_H

#include "kv_rpc_service_types.h"

namespace elasticmem { namespace storage {

class kv_rpc_serviceConstants {
 public:
  kv_rpc_serviceConstants();

};

extern const kv_rpc_serviceConstants g_kv_rpc_service_constants;

}} // namespace

#endif
