/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef block_registration_service_CONSTANTS_H
#define block_registration_service_CONSTANTS_H

#include "block_registration_service_types.h"

namespace jiffy { namespace directory {

class block_registration_serviceConstants {
 public:
  block_registration_serviceConstants();

};

extern const block_registration_serviceConstants g_block_registration_service_constants;

}} // namespace

#endif
