/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef maestro_allocator_service_CONSTANTS_H
#define maestro_allocator_service_CONSTANTS_H

#include "maestro_allocator_service_types.h"

namespace jiffy { namespace maestro {

class maestro_allocator_serviceConstants {
 public:
  maestro_allocator_serviceConstants();

};

extern const maestro_allocator_serviceConstants g_maestro_allocator_service_constants;

}} // namespace

#endif
